### ISSUE TITLE
部分书籍的作者获取有误

### ISSUE THREAD

**Issue by jasongzy** [acdzh/douban-book-api#1]
如《[三体](https://book.douban.com/subject/2567698/)》（`/isbn/9787536692930`）、《[大话数据结构](https://book.douban.com/subject/6424904/)》（`/isbn/9787302255659`），返回的作者列表都为：`"author":["\n        "]`

**Comment by acdzh** [comment]
感谢反馈, 我晚上检查一下解析规则

**Comment by acdzh** [comment]
换用了一种新的获取作者方式, 现在应该没问题了. 目前测试种类还不够, 后续如果发现其他解析错误, 辛苦也提下 issue.
