### ISSUE TITLE
[非bug] 技术请教

### ISSUE THREAD

**Issue by DreamAndDead** [acdzh/douban-book-api#5]
decrypt.js 是如何得到的？

https://github.com/acdzh/douban-book-api/blob/b461aec287f1fe7eef40e22353f5c4763950ec2b/src/douban/libs/decrypt.js

**Comment by acdzh** [comment]
断点分析来的, 如果我没记错的话, 应该是这个脚本https://img3.doubanio.com/dae/staticng/s/search/a2a1181bd6c0d2c97259e8597b3fcd3d47593e2e/dist/vendor.js 的一部分.
(代码结构可能有变化, 可以再断点看一下)
