### ISSUE TITLE
calibre插件的接口请求url好像有错误

### ISSUE THREAD

**Issue by AemonCao** [acdzh/douban-book-api#9]
api的搜索url是：`{HOST}/search?text=<text>`
而插件请求的url是：`{HOST}/search/<text>`，代码中的位置是：https://github.com/acdzh/douban-book-api/blob/eafa499f26b7fe933117de15cafdd34d69cc1914/calibre/__init__.py#L115

**Comment by AemonCao** [comment]
安装插件后请求，日志显示一直404，然后我按照这样 https://github.com/acdzh/douban-book-api/pull/10 修改后就可以正常刮削了。

**Comment by acdzh** [comment]
是的, 接口改过一次, 插件里的请求地址忘记一起改了
